Rss.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rss.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Rss.MVC/Controllers/RssItemController.cs
using DAL;
using PagedList;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;

namespace Rss.MVC.Controllers
{
    public class RssItemController : Controller
    {
        private ApplicationContext db = new ApplicationContext();

        int pageSize = 10;

        public RssItemController()
        {
            Mapper.Initialize(cfg => 
            cfg.CreateMap<RssItem, Rss.Contract.RssItem>()
            .ForMember(d => d.Description, opt => opt.MapFrom(v => v.Description != null ? (v.Description.StartsWith("<") ? "" : v.Description.Replace("<br", "")) : ""))
            );  
        }

        public async Task<ActionResult> Index(int? page)
        {
            var entityRssItems = await (from s in db.Rsses
                                  select s).ToListAsync();

            var contractRssItems =
                Mapper.Map<List<RssItem>, List<Rss.Contract.RssItem>>(entityRssItems);
            
            ViewBag.Hosts = contractRssItems.OrderBy(r => r.Host).Select(r => r.Host).Distinct().Select(x =>
                                 new SelectListItem()
                                 {
                                     Value = x.ToString(),
                                     Text = x.ToString()
                                 });

            int pageNumber = page ?? 1;
            return View(contractRssItems.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> IndexSearch(int? page, string sort, string resource)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            ViewBag.Sort = sort;
            ViewBag.Resource = resource;

            List<Contract.RssItem> contractRssItems = Session["rssItemList"] as List<Contract.RssItem>;

            string resourceState = Session["resourceState"] as string;
            string sortState = Session["sortState"] as string;

            if (contractRssItems == null || resource != resourceState || sort != sortState)
            {
                Session["resourceState"] = resource;
                Session["sortState"] = sort;

                var rssItems = from s in db.Rsses
                               select s;

                Session["rssItemList"] = rssItems;

                if (!string.IsNullOrEmpty(resource))
                {
                    rssItems = rssItems.Where(r => r.Host == resource);
                }

                switch (sort)
                {
                    case "Date":
                        rssItems = rssItems.OrderByDescending(s => s.Date);
                        break;
                    case "Url":
                        rssItems = rssItems
                            .OrderBy(s => s.Host);
                        break;
                    default:
                        break;
                }

                List<RssItem> rssItemList = await rssItems.ToListAsync();

                contractRssItems =
                    Mapper.Map<List<RssItem>, List<Rss.Contract.RssItem>>(rssItemList);
                
                Session["rssItemList"] = contractRssItems;
            }
            
            ViewBag.Hosts = contractRssItems.OrderBy(r => r.Host).Select(r => r.Host).Distinct().Select(x =>
                                  new SelectListItem()
                                  {
                                      Value = x.ToString(),
                                      Text = x.ToString()
                                  });

            int pageNumber = page ?? 1;
            return PartialView("_RssItemGrid", contractRssItems.ToPagedList(pageNumber, pageSize));
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Rss.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Rss.MVC/Views/RssItem/Index.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Новостная лента</h2>

@using (Ajax.BeginForm("IndexSearch", "RssItem", new AjaxOptions { UpdateTargetId = "results", HttpMethod = "post" }))
{
    @Html.AntiForgeryToken()
    <p>
        Источник ленты
        @Html.DropDownList("resource",
    new SelectList(ViewBag.Hosts as IEnumerable<SelectListItem>, "Value", "Text"),
    "Все",
    new { @class = "form-control" })

        @Html.RadioButton("sort", "Date") Сортировать по дате
        @Html.RadioButton("sort", "Url") Сортировать по источнику
    </p>
    <input type="submit" value="Посмотреть" />
}
<br />

<div id="results">
    @Html.Partial("~/Views/Shared/_RssItemGrid.cshtml")
</div>

Rss.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    @Scripts.Render("~/scripts/jquery-3.3.1.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


    @RenderSection("scripts", required: false)
</body>
</html>

Rss.MVC/Views/Shared/_RssItemGrid.cshtml
@model PagedList.IPagedList<Rss.Contract.RssItem>

@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<body>
    <table class="table">
        <tr>
            <th>
                Источник
            </th>
            <th>
                Название новости
            </th>
            <th>
                Описание новости
            </th>
            <th>
                Дата публикации
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <p>@Html.DisplayFor(modelItem => item.Host)</p>
                </td>
                <td>
                    <a href="@Html.DisplayFor(modelItem => item.Link)">@Html.DisplayFor(modelItem => item.Title)</a>
                </td>
                <td>
                    @if (!item.Description.StartsWith("<"))
                    {
                        @Html.DisplayFor(modelItem => item.Description)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
            </tr>
        }
    </table>

    <br />
    <div class="btn-group">
        <div id="pager">
            Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("IndexSearch",
                new { page = page, sort = ViewBag.Sort, resource = ViewBag.Resource }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.Classic,
        new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "Post",
            UpdateTargetId = "results"
        }))
        </div>
    </div>
</body>
</html>

@Scripts.Render("~/scripts/RssItem/Index.js")